# Omics - Analysis of large-scale biomolecular datasets

KIMN20 - LTH

Daniel Nilsson  
Massimiliano Volpe  
2025-10-29

## Introduction to R

### Course date: 04 November 2025

### Last modified: 2025-10-29

## Welcome to R Programming! 🐧

This presentation will teach you the fundamentals of R programming for
data analysis.

### What we’ll cover:

-   R language basics and getting help
-   Working with packages
-   Variables and data types
-   Data structures (vectors, matrices, lists, data frames)
-   Reading data from files
-   Writing functions

------------------------------------------------------------------------

## Getting Started with R

### Opening R/RStudio

-   **RStudio**: Download from
    https://posit.co/download/rstudio-desktop/
-   **Web-based**: Use RStudio Cloud or Google Colab with R kernel
-   **Command line**: Type `R` in terminal

### Your First R Commands

In [ ]:
# This is a comment - it won't execute
print("Hello, R!")

[1] "Hello, R!"

Try running this command in your R console!

------------------------------------------------------------------------

### R as a Calculator

In [ ]:
# Basic arithmetic
2 + 3

[1] 5

[1] 6

[1] 30

[1] 5

[1] 8

------------------------------------------------------------------------

## Getting Help

### Built-in Help Functions

In [ ]:
# Get help for a function
?print
help(print)

# Search for functions
??plot
help.search("plot")

### Help for Packages

In [ ]:
# Get help for installed packages
help(package = "base")

# Vignettes (detailed tutorials)
vignette()
# vignette("ggplot2")  # Commented out to prevent browser opening

------------------------------------------------------------------------

## Working with Packages

### Installing Packages

In [ ]:
# Commented out to prevent browser opening
# Install from CRAN (main repository)
# install.packages("tidyverse")

# Install multiple packages
# install.packages(c("dplyr", "ggplot2", "readr"))

### Loading Packages

In [ ]:
# Load a package
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

------------------------------------------------------------------------

### Package Management

In [ ]:
# See loaded packages
sessionInfo()

R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS 15.7.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Stockholm
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lubridate_1.9.4 forcats_1.0.0   stringr_1.5.1   dplyr_1.1.4    
 [5] purrr_1.0.2     readr_2.1.5     tidyr_1.3.1     tibble_3.2.1   
 [9] ggplot2_3.5.1   tidyverse_2.0.0

loaded via a namespace (and not attached):
 [1] gtable_0.3.6      jsonlite_1.8.9    compiler_4.4.1    tidyselect_1.2.1 
 [5] scales_1.3.0      yaml_2.3.10       fastmap_1.2.0     R6_2.5.1         
 [9] generics_0.1.3    knitr_1.50        munsell_0.5.

------------------------------------------------------------------------

## Variables and Assignment

### Creating Variables

In [ ]:
# Assignment operators
x <- 5
y = 10
20 -> z

# Print variables
x

[1] 5

[1] 10

------------------------------------------------------------------------

### Variable Names

In [ ]:
# Valid names
my_variable <- 1
myVariable <- 2
.variable <- 3
variable. <- 4

# Invalid names (would cause errors)
# 1variable <- 5
# my-variable <- 6
# my variable <- 7

------------------------------------------------------------------------

## Data Types and Classes

### Basic Data Types

In [ ]:
# Numeric (double)
num <- 3.14
class(num)

[1] "numeric"

[1] "integer"

[1] "character"

[1] "logical"

------------------------------------------------------------------------

### Type Checking

In [ ]:
# Check data types
is.numeric(num)

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

------------------------------------------------------------------------

## Type Casting and Conversion

### Converting Between Types

In [ ]:
# Numeric to character
as.character(3.14)

[1] "3.14"

[1] 42.5

[1] 3

[1] 1

[1] 0

------------------------------------------------------------------------

### Common Conversions

In [ ]:
# String to logical
as.logical("TRUE")

[1] TRUE

[1] FALSE

[1] "A" "B" "A"

------------------------------------------------------------------------

## Basic String Operations

### String Basics

In [ ]:
# Create strings
name <- "Alice"
greeting <- 'Hello'

# String length
nchar(name)

[1] 5

[1] "Hello World"

[1] "Hello World"

------------------------------------------------------------------------

### String Manipulation

In [ ]:
# Substring
substr("Hello World", 1, 5)

[1] "Hello"

[1] "HELLO"

[1] "world"

[[1]]
[1] "Hello" "World"

------------------------------------------------------------------------

## Atomic Vectors

### Creating Vectors

In [ ]:
# Numeric vector
numbers <- c(1, 2, 3, 4, 5)
numbers

[1] 1 2 3 4 5

[1] "apple"  "banana" "orange"

[1]  TRUE FALSE  TRUE

------------------------------------------------------------------------

### Vector Operations

In [ ]:
# Vector arithmetic
x <- c(1, 2, 3)
y <- c(4, 5, 6)
x + y

[1] 5 7 9

[1]  4 10 18

[1] 5

[1] 15

[1] 3

------------------------------------------------------------------------

### Vector Indexing

In [ ]:
# Access elements
fruits[1]       # First element

[1] "apple"

[1] "banana" "orange"

[1] "apple"  "orange"

[1] "banana" "orange"

[1] "banana"

------------------------------------------------------------------------

### Named Vectors

In [ ]:
# Create named vector
ages <- c(Alice = 25, Bob = 30, Carol = 35)
ages

Alice   Bob Carol 
   25    30    35 

Alice 
   25 

Alice Carol 
   25    35 

------------------------------------------------------------------------

## Matrices

### Creating Matrices

In [ ]:
# Create matrix from vector
matrix(1:9, nrow = 3, ncol = 3)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

------------------------------------------------------------------------

### Matrix Operations

In [ ]:
# Create sample matrix
m <- matrix(1:4, nrow = 2)
m

     [,1] [,2]
[1,]    1    3
[2,]    2    4

[1] 2 2

[1] 2

[1] 2

------------------------------------------------------------------------

### Matrix Indexing

In [ ]:
# Access elements
m[1, 2]    # Row 1, Column 2

[1] 3

[1] 1 3

[1] 3 4

[1] 1 2

------------------------------------------------------------------------

### Matrix Arithmetic

In [ ]:
# Matrix operations
m1 <- matrix(1:4, nrow = 2)
m2 <- matrix(5:8, nrow = 2)

m1 + m2

     [,1] [,2]
[1,]    6   10
[2,]    8   12

     [,1] [,2]
[1,]    5   21
[2,]   12   32

     [,1] [,2]
[1,]   23   31
[2,]   34   46

------------------------------------------------------------------------

## Lists

### Creating Lists

In [ ]:
# Simple list
my_list <- list(1, "hello", TRUE)
my_list

[[1]]
[1] 1

[[2]]
[1] "hello"

[[3]]
[1] TRUE

------------------------------------------------------------------------

### Creating Lists

In [ ]:
# Named list
person <- list(
  name = "Alice",
  age = 25,
  scores = c(85, 90, 88)
)
person

$name
[1] "Alice"

$age
[1] 25

$scores
[1] 85 90 88

------------------------------------------------------------------------

### Accessing List Elements

In [ ]:
# By index
person[[1]]  # First element

[1] "Alice"

[1] 85 90 88

[1] "Alice"

[1] 25

[1] 85 90 88

------------------------------------------------------------------------

### List Operations

In [ ]:
# List length
length(person)

[1] 3

[1] "name"   "age"    "scores"

$name
[1] "Alice"

$age
[1] 25

$scores
[1] 85 90 88

$city
[1] "Stockholm"

------------------------------------------------------------------------

### List Operations

In [ ]:
# Remove elements
person$city <- NULL
person

$name
[1] "Alice"

$age
[1] 25

$scores
[1] 85 90 88

------------------------------------------------------------------------

## Data Frames

### Creating Data Frames

In [ ]:
# Create data frame
students <- data.frame(
  name = c("Alice", "Bob", "Carol"),
  age = c(20, 21, 19),
  grade = c("A", "B", "A")
)
students

   name age grade
1 Alice  20     A
2   Bob  21     B
3 Carol  19     A

------------------------------------------------------------------------

### Data Frame Properties

In [ ]:
# Structure
str(students)

'data.frame':   3 obs. of  3 variables:
 $ name : chr  "Alice" "Bob" "Carol"
 $ age  : num  20 21 19
 $ grade: chr  "A" "B" "A"

[1] 3 3

[1] 3

[1] 3

[1] "name"  "age"   "grade"

------------------------------------------------------------------------

### Data Frame Indexing

In [ ]:
# Access columns
students

   name age grade
1 Alice  20     A
2   Bob  21     B
3 Carol  19     A

[1] "Alice" "Bob"   "Carol"

[1] 20 21 19

[1] 20 21 19

   name age grade
1 Alice  20     A

   name age grade
1 Alice  20     A
2   Bob  21     B

------------------------------------------------------------------------

In [ ]:
students

   name age grade
1 Alice  20     A
2   Bob  21     B
3 Carol  19     A

[1] 20

[1] 20

------------------------------------------------------------------------

### Data Frame Operations

In [ ]:
# Add column
students$passed <- c(TRUE, TRUE, FALSE)
students

   name age grade passed
1 Alice  20     A   TRUE
2   Bob  21     B   TRUE
3 Carol  19     A  FALSE

     name                age          grade             passed       
 Length:3           Min.   :19.0   Length:3           Mode :logical  
 Class :character   1st Qu.:19.5   Class :character   FALSE:1        
 Mode  :character   Median :20.0   Mode  :character   TRUE :2        
                    Mean   :20.0                                     
                    3rd Qu.:20.5                                     
                    Max.   :21.0                                     

------------------------------------------------------------------------

### Data Frame Operations

In [ ]:
# View first/last rows
head(students)

   name age grade passed
1 Alice  20     A   TRUE
2   Bob  21     B   TRUE
3 Carol  19     A  FALSE

   name age grade passed
1 Alice  20     A   TRUE
2   Bob  21     B   TRUE
3 Carol  19     A  FALSE

------------------------------------------------------------------------

## Reading Data

### Reading CSV Files

In [ ]:
# Read CSV file
data <- read.csv("assets/data.csv")
head(data)

  Gene_Symbol         Gene_ID Control_1 Control_2 Treatment_1 Treatment_2
1       GAPDH ENSG00000111640      1250      1180         980        1050
2        ACTB ENSG00000075624       890       920         750         820
3        TP53 ENSG00000141510       450       480         680         720
4         MYC ENSG00000136997       320       350         580         620
5        EGFR ENSG00000146648       180       200         450         480
6       BRCA1 ENSG00000012048       150       170         380         410

------------------------------------------------------------------------

### Reading CSV Files

Factors in R are a special data type used to represent categorical data
with predefined levels. They’re like labeled categories that can be
ordered or unordered. stringsAsFactors = FALSE prevents automatic
conversion of strings to factors.

In [ ]:
# With custom options
data <- read.csv("assets/data.csv", 
                 header = TRUE,
                 sep = ",",
                 stringsAsFactors = FALSE)
head(data)

  Gene_Symbol         Gene_ID Control_1 Control_2 Treatment_1 Treatment_2
1       GAPDH ENSG00000111640      1250      1180         980        1050
2        ACTB ENSG00000075624       890       920         750         820
3        TP53 ENSG00000141510       450       480         680         720
4         MYC ENSG00000136997       320       350         580         620
5        EGFR ENSG00000146648       180       200         450         480
6       BRCA1 ENSG00000012048       150       170         380         410

------------------------------------------------------------------------

### Reading Excel Files

In [ ]:
# Install readxl if needed
# install.packages("readxl")
library(readxl)

# Read Excel file
excel_data <- read_excel("assets/data.xlsx")
head(excel_data)

# A tibble: 6 × 6
  Gene_Symbol Gene_ID         Control_1 Control_2 Treatment_1 Treatment_2
  <chr>       <chr>               <dbl>     <dbl>       <dbl>       <dbl>
1 GAPDH       ENSG00000111640      1250      1180         980        1050
2 ACTB        ENSG00000075624       890       920         750         820
3 TP53        ENSG00000141510       450       480         680         720
4 MYC         ENSG00000136997       320       350         580         620
5 EGFR        ENSG00000146648       180       200         450         480
6 BRCA1       ENSG00000012048       150       170         380         410

# A tibble: 6 × 6
  Gene_Symbol Gene_ID         Control_1 Control_2 Treatment_1 Treatment_2
  <chr>       <chr>               <dbl>     <dbl>       <dbl>       <dbl>
1 GAPDH       ENSG00000111640      1250      1180         980        1050
2 ACTB        ENSG00000075624       890       920         750         820
3 TP53        ENSG00000141510       450       480         680         720
4 MYC         ENSG00000136997       320       350         580         620
5 EGFR        ENSG00000146648       180       200         450         480
6 BRCA1       ENSG00000012048       150       170         380         410

------------------------------------------------------------------------

### Other File Formats

In [ ]:
# Read tab-separated file
tsv_data <- read.delim("assets/data.tsv")
head(tsv_data)

  Gene_Symbol         Gene_ID Control_1 Control_2 Treatment_1 Treatment_2
1       GAPDH ENSG00000111640      1250      1180         980        1050
2        ACTB ENSG00000075624       890       920         750         820
3        TP53 ENSG00000141510       450       480         680         720
4         MYC ENSG00000136997       320       350         580         620
5        EGFR ENSG00000146648       180       200         450         480
6       BRCA1 ENSG00000012048       150       170         380         410

------------------------------------------------------------------------

## Writing Functions

### Basic Function Structure

In [ ]:
# Simple function
greet <- function(name) {
  message <- paste("Hello,", name, "!")
  return(message)
}

# Call the function
greet("Alice")

[1] "Hello, Alice !"

### Functions with Multiple Parameters

In [ ]:
# Function with multiple parameters
calculate_bmi <- function(weight_kg, height_m) {
  bmi <- weight_kg / (height_m^2)
  return(bmi)
}

# Usage
calculate_bmi(70, 1.75)

[1] 22.85714

------------------------------------------------------------------------

### Functions with Default Values

In [ ]:
# Function with defaults
power_function <- function(x, power = 2) {
  result <- x^power
  return(result)
}

# Usage
power_function(3)      # Uses default power = 2

[1] 9

[1] 27

------------------------------------------------------------------------

### Functions with Conditional Logic

In [ ]:
# Function with if-else
grade_letter <- function(score) {
  if (score >= 90) {
    return("A")
  } else if (score >= 80) {
    return("B")
  } else if (score >= 70) {
    return("C")
  } else {
    return("F")
  }
}

# Usage
grade_letter(85)

[1] "B"

[1] "A"

------------------------------------------------------------------------

## Practice Time! 💻

### Exercise 1: Variables and Types

1.  Create variables for your name, age, and height
2.  Check their data types with `class()`
3.  Convert your age to character and height to integer

In [ ]:
# Your code here
name <- "Your Name"
age <- 25
height <- 1.75

class(name)

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "25"

[1] 1

------------------------------------------------------------------------

### Exercise 2: Vectors and Data Frames

1.  Create a vector of your favorite numbers
2.  Create a data frame with names and scores
3.  Calculate the mean of the scores

In [ ]:
# Your code here
numbers <- c(1, 5, 10, 15, 20)

scores_df <- data.frame(
  name = c("Alice", "Bob", "Carol"),
  score = c(85, 92, 78)
)

mean(scores_df$score)

[1] 85

------------------------------------------------------------------------

## Quiz Time! 🧠

### Question 1

Which operator is used for assignment in R? - A) `=` - B) `<-` - C) Both
A and B

### Question 2

What function creates a vector in R? - A) `vector()` - B) `c()` - C)
`make_vector()`

### Question 3

How do you access the first element of a vector named `my_vec`? - A)
`my_vec[0]` - B) `my_vec[1]` - C) `my_vec.first`

*(Answers: 1-C, 2-B, 3-B)*

------------------------------------------------------------------------

## Thank You!

You’ve completed the basic R programming tutorial!

### Remember:

-   Use `?function_name` for help
-   Install packages with `install.packages()`
-   Load packages with `library()`
-   Practice regularly with real data

### Questions?

Feel free to ask your instructor or classmates!

🐧 Happy R programming! 🐧

------------------------------------------------------------------------

## Next Steps

### What to Learn Next

-   Data manipulation with dplyr
-   Data visualization with ggplot2
-   Statistical analysis functions
-   Writing R scripts and RMarkdown
-   Advanced data structures
-   Working with dates and times

### Resources

-   [R for Data Science](https://r4ds.had.co.nz/) - Free online book
-   [RStudio Education](https://education.rstudio.com/) - Learning
    resources
-   [CRAN Task Views](https://cran.r-project.org/web/views/) - Package
    collections
-   [R Documentation](https://www.rdocumentation.org/) - Function
    reference